// This file was automatically generated by 'Kmisc::registerFunctions()'

#include <R.h>
#include <Rinternals.h>

#include <R_ext/Rdynload.h>

SEXP chromVAR_pwm_euclidean(SEXP mat1SEXP, SEXP mat2SEXP);
SEXP chromVAR_pwm_dist_single(SEXP mat1SEXP, SEXP mat2SEXP, SEXP min_overlapSEXP);
SEXP chromVAR_compute_pwm_dist(SEXP pwmsSEXP, SEXP min_overlapSEXP);
SEXP chromVAR_compute_pwm_dist2(SEXP pwmsSEXP, SEXP pwms2SEXP, SEXP min_overlapSEXP);
SEXP chromVAR_col_sds(SEXP XSEXP, SEXP na_rmSEXP);
SEXP chromVAR_row_sds(SEXP XSEXP, SEXP na_rmSEXP);
SEXP chromVAR_row_sds_perm(SEXP XSEXP, SEXP na_rmSEXP);
SEXP chromVAR_ProbSampleReplace(SEXP sizeSEXP, SEXP probSEXP);
SEXP chromVAR_bg_sample_helper(SEXP bin_membershipSEXP, SEXP bin_pSEXP, SEXP bin_densitySEXP, SEXP niterationsSEXP);
SEXP chromVAR_euc_dist(SEXP xSEXP);

R_CallMethodDef callMethods[]  = {
  {"chromVAR_pwm_euclidean", (DL_FUNC) &chromVAR_pwm_euclidean, 2},
  {"chromVAR_pwm_dist_single", (DL_FUNC) &chromVAR_pwm_dist_single, 3},
  {"chromVAR_compute_pwm_dist", (DL_FUNC) &chromVAR_compute_pwm_dist, 2},
  {"chromVAR_compute_pwm_dist2", (DL_FUNC) &chromVAR_compute_pwm_dist2, 3},
  {"chromVAR_col_sds", (DL_FUNC) &chromVAR_col_sds, 2},
  {"chromVAR_row_sds", (DL_FUNC) &chromVAR_row_sds, 2},
  {"chromVAR_row_sds_perm", (DL_FUNC) &chromVAR_row_sds_perm, 2},
  {"chromVAR_ProbSampleReplace", (DL_FUNC) &chromVAR_ProbSampleReplace, 2},
  {"chromVAR_bg_sample_helper", (DL_FUNC) &chromVAR_bg_sample_helper, 4},
  {"chromVAR_euc_dist", (DL_FUNC) &chromVAR_euc_dist, 1},
  {NULL, NULL, 0}
};

void R_init_chromVAR(DllInfo *info) {
  R_registerRoutines(info, NULL, callMethods, NULL, NULL);
  R_useDynamicSymbols(info, FALSE);
}

