// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// ProbSampleReplace
arma::urowvec ProbSampleReplace(int size, arma::vec prob);
RcppExport SEXP chromVAR_ProbSampleReplace(SEXP sizeSEXP, SEXP probSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prob(probSEXP);
    __result = Rcpp::wrap(ProbSampleReplace(size, prob));
    return __result;
END_RCPP
}
// bg_sample_helper
arma::umat bg_sample_helper(arma::uvec bin_membership, arma::mat bin_p, arma::vec bin_density, arma::uword niterations);
RcppExport SEXP chromVAR_bg_sample_helper(SEXP bin_membershipSEXP, SEXP bin_pSEXP, SEXP bin_densitySEXP, SEXP niterationsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::uvec >::type bin_membership(bin_membershipSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type bin_p(bin_pSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type bin_density(bin_densitySEXP);
    Rcpp::traits::input_parameter< arma::uword >::type niterations(niterationsSEXP);
    __result = Rcpp::wrap(bg_sample_helper(bin_membership, bin_p, bin_density, niterations));
    return __result;
END_RCPP
}
// euc_dist
arma::mat euc_dist(arma::mat x);
RcppExport SEXP chromVAR_euc_dist(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    __result = Rcpp::wrap(euc_dist(x));
    return __result;
END_RCPP
}
// downsample_dense
NumericMatrix downsample_dense(NumericMatrix X, double p);
RcppExport SEXP chromVAR_downsample_dense(SEXP XSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    __result = Rcpp::wrap(downsample_dense(X, p));
    return __result;
END_RCPP
}
// pwm_euclidean
double pwm_euclidean(arma::mat mat1, arma::mat mat2);
RcppExport SEXP chromVAR_pwm_euclidean(SEXP mat1SEXP, SEXP mat2SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type mat1(mat1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mat2(mat2SEXP);
    __result = Rcpp::wrap(pwm_euclidean(mat1, mat2));
    return __result;
END_RCPP
}
// pwm_dist_single
arma::vec pwm_dist_single(arma::mat mat1, arma::mat mat2);
RcppExport SEXP chromVAR_pwm_dist_single(SEXP mat1SEXP, SEXP mat2SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type mat1(mat1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mat2(mat2SEXP);
    __result = Rcpp::wrap(pwm_dist_single(mat1, mat2));
    return __result;
END_RCPP
}
// compute_pwm_dist
List compute_pwm_dist(List pwms);
RcppExport SEXP chromVAR_compute_pwm_dist(SEXP pwmsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type pwms(pwmsSEXP);
    __result = Rcpp::wrap(compute_pwm_dist(pwms));
    return __result;
END_RCPP
}
// col_sds
NumericVector col_sds(arma::mat& X, bool na_rm);
RcppExport SEXP chromVAR_col_sds(SEXP XSEXP, SEXP na_rmSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    __result = Rcpp::wrap(col_sds(X, na_rm));
    return __result;
END_RCPP
}
// row_sds
NumericVector row_sds(arma::mat& X, bool na_rm);
RcppExport SEXP chromVAR_row_sds(SEXP XSEXP, SEXP na_rmSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    __result = Rcpp::wrap(row_sds(X, na_rm));
    return __result;
END_RCPP
}
// row_sds_perm
NumericVector row_sds_perm(arma::mat& X, bool na_rm);
RcppExport SEXP chromVAR_row_sds_perm(SEXP XSEXP, SEXP na_rmSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    __result = Rcpp::wrap(row_sds_perm(X, na_rm));
    return __result;
END_RCPP
}
