# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ProbSampleReplace <- function(size, prob) {
    .Call('chromVAR_ProbSampleReplace', PACKAGE = 'chromVAR', size, prob)
}

bg_sample_helper <- function(bin_membership, bin_p, bin_density, niterations) {
    .Call('chromVAR_bg_sample_helper', PACKAGE = 'chromVAR', bin_membership, bin_p, bin_density, niterations)
}

euc_dist <- function(x) {
    .Call('chromVAR_euc_dist', PACKAGE = 'chromVAR', x)
}

downsample_dense <- function(X, p) {
    .Call('chromVAR_downsample_dense', PACKAGE = 'chromVAR', X, p)
}

pwm_euclidean <- function(mat1, mat2) {
    .Call('chromVAR_pwm_euclidean', PACKAGE = 'chromVAR', mat1, mat2)
}

pwm_dist_single <- function(mat1, mat2) {
    .Call('chromVAR_pwm_dist_single', PACKAGE = 'chromVAR', mat1, mat2)
}

compute_pwm_dist <- function(pwms) {
    .Call('chromVAR_compute_pwm_dist', PACKAGE = 'chromVAR', pwms)
}

get_thresholds <- function(mats, nuc_freqs, p) {
    .Call('chromVAR_get_thresholds', PACKAGE = 'chromVAR', mats, nuc_freqs, p)
}

get_motif_ix <- function(mats, x, nuc_freqs, p, w) {
    .Call('chromVAR_get_motif_ix', PACKAGE = 'chromVAR', mats, x, nuc_freqs, p, w)
}

get_max_motif_score <- function(mats, x, nuc_freqs, p, w) {
    .Call('chromVAR_get_max_motif_score', PACKAGE = 'chromVAR', mats, x, nuc_freqs, p, w)
}

get_motif_positions <- function(mats, x, nuc_freqs, p, w) {
    .Call('chromVAR_get_motif_positions', PACKAGE = 'chromVAR', mats, x, nuc_freqs, p, w)
}

col_sds <- function(X, na_rm = FALSE) {
    .Call('chromVAR_col_sds', PACKAGE = 'chromVAR', X, na_rm)
}

row_sds <- function(X, na_rm = FALSE) {
    .Call('chromVAR_row_sds', PACKAGE = 'chromVAR', X, na_rm)
}

row_sds_perm <- function(X, na_rm = FALSE) {
    .Call('chromVAR_row_sds_perm', PACKAGE = 'chromVAR', X, na_rm)
}

