# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ProbSampleReplace <- function(size, prob) {
    .Call('chromVAR_ProbSampleReplace', PACKAGE = 'chromVAR', size, prob)
}

bg_sample_helper <- function(bin_membership, bin_p, bin_density, niterations) {
    .Call('chromVAR_bg_sample_helper', PACKAGE = 'chromVAR', bin_membership, bin_p, bin_density, niterations)
}

euc_dist <- function(x) {
    .Call('chromVAR_euc_dist', PACKAGE = 'chromVAR', x)
}

maha_density <- function(ix, X1, X2, s, w = 0.1) {
    .Call('chromVAR_maha_density', PACKAGE = 'chromVAR', ix, X1, X2, s, w)
}

bg_sample <- function(ix, X1, X2, s, dens, n, w = 0.1) {
    .Call('chromVAR_bg_sample', PACKAGE = 'chromVAR', ix, X1, X2, s, dens, n, w)
}

get_normalized_counts <- function(counts, expectation, fragments_per_sample) {
    .Call('chromVAR_get_normalized_counts', PACKAGE = 'chromVAR', counts, expectation, fragments_per_sample)
}

p_to_score <- function(pwm, bg, p) {
    .Call('chromVAR_p_to_score', PACKAGE = 'chromVAR', pwm, bg, p)
}

motif_match <- function(mat, x, nuc_freqs, p) {
    .Call('chromVAR_motif_match', PACKAGE = 'chromVAR', mat, x, nuc_freqs, p)
}

motif_match_score <- function(mat, x) {
    .Call('chromVAR_motif_match_score', PACKAGE = 'chromVAR', mat, x)
}

pwm_euclidean <- function(mat1, mat2) {
    .Call('chromVAR_pwm_euclidean', PACKAGE = 'chromVAR', mat1, mat2)
}

pwm_dist_single <- function(mat1, mat2) {
    .Call('chromVAR_pwm_dist_single', PACKAGE = 'chromVAR', mat1, mat2)
}

compute_pwm_dist <- function(pwms) {
    .Call('chromVAR_compute_pwm_dist', PACKAGE = 'chromVAR', pwms)
}

