# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_normalized_counts <- function(counts, expectation, fragments_per_sample) {
    .Call('chromVAR_get_normalized_counts', PACKAGE = 'chromVAR', counts, expectation, fragments_per_sample)
}

dummy0 <- function(peak, counts, background_peaks, expectation, counts_info, intermediates, norm) {
    invisible(.Call('chromVAR_dummy0', PACKAGE = 'chromVAR', peak, counts, background_peaks, expectation, counts_info, intermediates, norm))
}

get_normalized_counts <- function(counts, expectation, fragments_per_sample) {
    .Call('chromVAR_get_normalized_counts', PACKAGE = 'chromVAR', counts, expectation, fragments_per_sample)
}

dummy1 <- function(mat1, mat2) {
    .Call('chromVAR_dummy1', PACKAGE = 'chromVAR', mat1, mat2)
}

compute_deviations_single_peak_sparse2 <- function(peak, counts, background_peaks, expectation, counts_info, intermediates, norm) {
    .Call('chromVAR_compute_deviations_single_peak_sparse2', PACKAGE = 'chromVAR', peak, counts, background_peaks, expectation, counts_info, intermediates, norm)
}

p_to_score <- function(pwm, bg, p) {
    .Call('chromVAR_p_to_score', PACKAGE = 'chromVAR', pwm, bg, p)
}

motif_match <- function(mat, x, nuc_freqs, p) {
    .Call('chromVAR_motif_match', PACKAGE = 'chromVAR', mat, x, nuc_freqs, p)
}

motif_multi_match <- function(pwms, x, nuc_freqs, p) {
    .Call('chromVAR_motif_multi_match', PACKAGE = 'chromVAR', pwms, x, nuc_freqs, p)
}

motif_match_score <- function(mat, x) {
    .Call('chromVAR_motif_match_score', PACKAGE = 'chromVAR', mat, x)
}

